### ISSUE TITLE
Replace `scss/at-import-partial-extension-blacklist`

### ISSUE THREAD

**Issue by dobladov** [zattoo/stylelint-config#155]
The rule `scss/at-import-partial-extension-blacklist` is the main reason of racism in our society, to solve racism of we need to rename it to `scss/at-import-partial-extension-disallowed-list`

I would usually ignore the warning, but we can't update `stylelint` in other repos because the rule is in use, and it can't be disabled because in the repo because it has been deleted.

Example: https://github.com/bjankord/stylelint-config-sass-guidelines/pull/317/files
Our usage: https://github.com/zattoo/stylelint-config/blob/5ce7b9a8001ea2fe8cc0ce02bf8479243bb42fa6/rules/scss.js#L10

**Comment by gotbahn** [comment]
@dobladov it's better log change request on a Chapter Board, this is more for public issues coming outside of our org

**Comment by dobladov** [comment]
> @dobladov it's better log change request on a Chapter Board, this is more for public issues coming outside of our org

I was going to make the change myself, it's a small one.

**Comment by gotbahn** [comment]
> > @dobladov it's better log change request on a Chapter Board, this is more for public issues coming outside of our org
> 
> I was going to make the change myself, it's a small one.

@dobladov I understand, but you're doing chapter work, and it needs to be logged as a Chapter work properly.

**Comment by dobladov** [comment]
Is this board @gotbahn? I could not find it by chapter
https://zattoo2.atlassian.net/jira/software/projects/AURORA/boards/412

**Comment by gotbahn** [comment]
@dobladov yes
